[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_minigame = "3hdVVxxUCM7oGVxRYphvRaNziwmDWy4KARy9AFNmXeMS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mcshell/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
